parameters:
  - name: pulumi_backend_resource_group
    type: string
    default: Pulumi
    
  - name: pulumi_backend_location
    type: string
    default: WestEurope
    
  - name: pulumi_keyvault_key
    type: string
    default: pulumi
    
  - name: secrets_provider_keyvault_name
    type: string
    default: $(secrets-provider-keyvault-name)

  - name: backend_storage_account_name
    type: string
    default: $(backend-storage-account-name)
    
  - name: azure_subscription
    type: string
    default: $(azure-subscription)

pool:
  vmImage: ubuntu-latest

stages:

- stage: Set_up
  displayName: Set up deployment resources
  dependsOn: []
  jobs:
    - job: Pulumi
      steps:

      - task: DownloadBuildArtifacts@0
        displayName: Download build artifacts for API
        inputs:
          buildType: specific
          project: '44f232b3-0809-4f97-bac6-30d169f0187d'
          pipeline: '4'
          specificBuildWithTriggering: true
          buildVersionToDownload: latest
          downloadType: single
          artifactName: UnoCash.Api
          downloadPath: $(System.ArtifactsDirectory)

      - task: AzureCLI@2
        displayName: Create backend storage
        env:
          PULUMI_CONFIG_PASSPHRASE:
          AZURE_STORAGE_ACCOUNT: ${{ parameters.backend_storage_account_name }}
        inputs:
          azureSubscription: ${{ parameters.azure_subscription }}
          scriptType: bash
          scriptLocation: inlineScript
          addSpnToEnvironment: true
          inlineScript: |
            az group create \
              -l ${{ parameters.pulumi_backend_location }} \
              -n ${{ parameters.pulumi_backend_resource_group }}
            az storage account create \
              -n ${{ parameters.backend_storage_account_name }} \
              -g ${{ parameters.pulumi_backend_resource_group }} \
              -l ${{ parameters.pulumi_backend_location }} \
              --sku Standard_LRS
            az storage container create \
              -n unocash \
              --account-name ${{ parameters.backend_storage_account_name }}
            az keyvault create \
              --location ${{ parameters.pulumi_backend_location }} \
              --name ${{ parameters.secrets_provider_keyvault_name }} \
              --resource-group ${{ parameters.pulumi_backend_resource_group }}
            az keyvault set-policy \
              --name ${{ parameters.secrets_provider_keyvault_name }} \
              --key-permissions encrypt \
              --object-id $(az ad sp show --id $servicePrincipalId --query objectId -o tsv)
            az keyvault key create \
              --name ${{ parameters.pulumi_keyvault_key }} \
              --vault-name ${{ parameters.secrets_provider_keyvault_name }}

            export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
            export SAS_END=$(date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ')
            export AZURE_STORAGE_SAS_TOKEN=$(az storage account generate-sas \
              --permissions cdlruwap \
              --account-name ${{ parameters.backend_storage_account_name }} \
              --services b \
              --resource-types co \
              --expiry $SAS_END \
              -o tsv)

            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            export PATH="$PATH:/home/vsts/.pulumi/bin"
            export KEYVAULT="${{ parameters.secrets_provider_keyvault_name }}.vault.azure.net"

            curl -fsSL https://get.pulumi.com | sh

            pulumi login -c azblob://unocash -C UnoCash.Pulumi

            pulumi stack select dev \
              -c \
              -C UnoCash.Pulumi \
              --secrets-provider="azurekeyvault://$KEYVAULT/keys/pulumi"

            pulumi config set ApiBuild "$(System.ArtifactsDirectory)"
            pulumi preview -C UnoCash.Pulumi
      
      - task: Cache@2
        displayName: Cache Pulumi installation
        inputs:
          key: pulumi
          path: /home/vsts/.pulumi

- stage: Development_preview
  displayName: Development preview
  dependsOn: Set_up
  jobs:
    - job: Preview
      steps:
        - task: AzureCLI@2
          displayName: Pulumi preview
          env:
            PULUMI_CONFIG_PASSPHRASE:
            AZURE_STORAGE_ACCOUNT: ${{ parameters.backend_storage_account_name }}
          inputs:
            azureSubscription: ${{ parameters.azure_subscription }}
            scriptType: bash
            scriptLocation: inlineScript
            addSpnToEnvironment: true
            inlineScript: |
              export PATH="$PATH:/home/vsts/.pulumi/bin"
              ls /home/vsts/.pulumi
              pulumi preview -C UnoCash.Pulumi

- stage: Development_deploy
  displayName: Development deploy
  dependsOn: Development_preview
  jobs:
    - deployment: Up
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureCLI@2
              displayName: Pulumi up
              env:
                PULUMI_CONFIG_PASSPHRASE:
                AZURE_STORAGE_ACCOUNT: ${{ parameters.backend_storage_account_name }}
              inputs:
                azureSubscription: ${{ parameters.azure_subscription }}
                scriptType: bash
                scriptLocation: inlineScript
                addSpnToEnvironment: true
                inlineScript: |
                  echo "Placeholder"