trigger:
  branches: 
    include:
    - master
  paths:
    include:
    - UnoCash.Login/*

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Create tool manifest
  inputs:
    command: custom
    custom: new
    arguments: tool-manifest --force
    workingDirectory: UnoCash.Login

- task: DotNetCoreCLI@2
  displayName: Install FAKE
  inputs:
    command: custom
    custom: tool
    arguments: install fake-cli
    workingDirectory: UnoCash.Login

- task: DotNetCoreCLI@2
  displayName: Install Paket
  inputs:
    command: custom
    custom: tool
    arguments: install paket
    workingDirectory: UnoCash.Login
    
- task: DotNetCoreCLI@2
  displayName: Build Fable project
  inputs:
    command: custom
    custom: fake
    arguments: build
    workingDirectory: UnoCash.Login

- task: PublishBuildArtifacts@1
  displayName: Publish Fable project
  inputs:
    pathtoPublish: UnoCash.Login/output
    artifactName: UnoCash.Login