trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Build Function API
  inputs:
    command: publish
    publishWebProjects: false
    projects: UnoCash.Api/UnoCash.Api.csproj
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: Publish Function API
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: UnoCash.Api