trigger:
  branches: 
    include:
    - master
  paths:
    exclude:
    - UnoCash.Pulumi/*
    - UnoCash.DevOps/release.yml

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Create tool manifest
  inputs:
    command: custom
    custom: new
    arguments: tool-manifest --force
    workingDirectory: UnoCash.Fulma

- task: DotNetCoreCLI@2
  displayName: Install FAKE
  inputs:
    command: custom
    custom: tool
    arguments: install fake-cli
    workingDirectory: UnoCash.Fulma

- task: DotNetCoreCLI@2
  displayName: Install Paket
  inputs:
    command: custom
    custom: tool
    arguments: install paket
    workingDirectory: UnoCash.Fulma
    
- task: DotNetCoreCLI@2
  displayName: Build Fable project
  inputs:
    command: custom
    custom: fake
    arguments: build
    workingDirectory: UnoCash.Fulma

- task: PublishBuildArtifacts@1
  displayName: Publish Fable project
  inputs:
    pathtoPublish: UnoCash.Fulma/output
    artifactName: UnoCash.Fulma
  
- task: DotNetCoreCLI@2
  displayName: Build Function API
  inputs:
    command: publish
    publishWebProjects: false
    projects: UnoCash.Api/UnoCash.Api.csproj
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
  
- task: PublishBuildArtifacts@1
  displayName: Publish Function API
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: UnoCash.Api