parameters:
  - name: secrets_provider_keyvault_name
    type: string
    default: $(secrets-provider-keyvault-name)

  - name: backend_storage_account_name
    type: string
    default: $(backend-storage-account-name)

  - name: azure_subscription
    type: string
    default: $(azure-subscription)

trigger: none

pool:
  vmImage: ubuntu-latest

stages:

  - stage: Development_destroy
    displayName: Development destroy
    jobs:
      - deployment: Destroy
        environment: dev_destroy
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: UseDotNet@2
                  displayName: 'Use .NET Core SDK 3.1.103'
                  inputs:
                    packageType: sdk
                    version: 3.1.103
                    installationPath: $(Agent.ToolsDirectory)/dotnet

                - task: AzureCLI@2
                  displayName: Pulumi destroy
                  env:
                    PULUMI_CONFIG_PASSPHRASE:
                    AZURE_STORAGE_ACCOUNT: ${{ parameters.backend_storage_account_name }}
                  inputs:
                    azureSubscription: ${{ parameters.azure_subscription }}
                    scriptType: bash
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    inlineScript: |
                      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                      export SAS_END=$(date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ')
                      export AZURE_STORAGE_SAS_TOKEN=$(az storage account generate-sas \
                        --permissions lrwc \
                        --account-name ${{ parameters.backend_storage_account_name }} \
                        --services b \
                        --resource-types co \
                        --expiry $SAS_END \
                        -o tsv)

                      export ARM_CLIENT_ID=$servicePrincipalId
                      export ARM_CLIENT_SECRET=$servicePrincipalKey
                      export ARM_TENANT_ID=$tenantId
                      export PATH="$PATH:/home/vsts/.pulumi/bin"
                      export KEYVAULT="${{ parameters.secrets_provider_keyvault_name }}.vault.azure.net"

                      curl -fsSL https://get.pulumi.com | sh

                      pulumi login -c azblob://unocash -C UnoCash.Pulumi

                      pulumi stack select dev \
                        -C UnoCash.Pulumi \
                        --secrets-provider="azurekeyvault://$KEYVAULT/keys/pulumi"

                      pulumi destroy -C UnoCash.Pulumi --yes